'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowLeft, Copy, RotateCcw, ChevronDown, ChevronUp, FileText, Type, Hash, MessageSquare, Layout } from 'lucide-react';
import Head from 'next/head';

export default function WordCounterPage() {
  const [text, setText] = useState('');
  const [stats, setStats] = useState({
    characters: 0,
    charactersNoSpaces: 0,
    words: 0,
    sentences: 0,
    paragraphs: 0
  });

  // SEO Section Dropdown States
  const [openSections, setOpenSections] = useState({
    whatItDoes: true,
    useCases: false,
    howToUse: false,
    examples: false,
    faqs: false
  });

  const toggleSection = (section: keyof typeof openSections) => {
    setOpenSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  // FAQ Data
  const faqData = [
    {
      question: "What counts as a word in this word counter?",
      answer: "A word is defined as any sequence of characters separated by spaces or punctuation. Our counter follows standard linguistic rules: 'hello-world' counts as one word, numbers like '123' count as words, and contractions like 'don't' count as a single word. The tool accurately handles multiple spaces, tabs, and line breaks."
    },
    {
      question: "How does the character counter differ from character count without spaces?",
      answer: "Character count includes every single character in your text: letters, numbers, punctuation, spaces, and line breaks. Character count without spaces excludes only space characters (regular spaces, tabs, and line breaks). This is useful for platforms with strict character limits like Twitter or SMS messages."
    },
    {
      question: "What constitutes a sentence in the sentence counter?",
      answer: "A sentence is defined as text ending with a period, exclamation mark, or question mark, followed by a space or end of text. Our counter handles abbreviations (like 'Dr.' or 'U.S.A.') correctly and doesn't count them as sentence endings. Multiple punctuation marks (!!! or ...) are treated as ending a single sentence."
    },
    {
      question: "How accurate is the paragraph counting?",
      answer: "Paragraphs are counted based on text blocks separated by one or more blank lines (line breaks). A single line break doesn't create a new paragraph—only when there's an empty line between text blocks. This matches standard word processing software and publishing conventions for paragraph separation."
    },
    {
      question: "Does this word counter work with different languages?",
      answer: "Yes, our word counter works with all languages that use space-separated words, including English, Spanish, French, German, and many others. For languages without spaces between words (like Chinese, Japanese, or Thai), character counting works perfectly, but word counting may differ as those languages have different word segmentation rules."
    }
  ];

  useEffect(() => {
    const characters = text.length;
    const charactersNoSpaces = text.replace(/\s/g, '').length;
    const words = text.trim() === '' ? 0 : text.trim().split(/\s+/).length;
    const sentences = text.trim() === '' ? 0 : text.split(/[.!?]+/).filter(s => s.trim().length > 0).length;
    const paragraphs = text.trim() === '' ? 0 : text.split(/\n\s*\n/).filter(p => p.trim().length > 0).length;

    setStats({
      characters,
      charactersNoSpaces,
      words,
      sentences,
      paragraphs
    });
  }, [text]);

  const handleClear = () => {
    setText('');
  };

  const handleCopy = async () => {
    const statsText = `Word Counter Results:\n\nCharacters: ${stats.characters}\nCharacters (no spaces): ${stats.charactersNoSpaces}\nWords: ${stats.words}\nSentences: ${stats.sentences}\nParagraphs: ${stats.paragraphs}\n\nGenerated by GrockTool.com Word Counter`;
    try {
      await navigator.clipboard.writeText(statsText);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <>
      <Head>
        <title>Word Counter | Free Online Character & Word Count Tool - GrockTool.com</title>
        <meta name="description" content="Free word counter tool that counts characters (with/without spaces), words, sentences, and paragraphs in real-time. Perfect for writers, students, and professionals." />
        <meta name="keywords" content="word counter, character counter, sentence counter, paragraph counter, word count tool, text analysis, writing tool, word calculator, text counter" />
        <meta property="og:title" content="Word Counter | Free Online Character & Word Count Tool - GrockTool.com" />
        <meta property="og:description" content="Instantly count words, characters, sentences, and paragraphs with our free real-time word counter tool. No limits, no registration required." />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Word Counter - GrockTool.com" />
        <meta name="twitter:description" content="Free online word and character counter with real-time statistics and analysis." />
        <link rel="canonical" href="https://grocktool.com/text-tools/word-counter" />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "Word Counter Tool",
            "applicationCategory": "WritingApplication",
            "operatingSystem": "Any",
            "description": "Free real-time word counter tool that counts characters, words, sentences, and paragraphs instantly",
            "url": "https://grocktool.com/text-tools/word-counter",
            "author": {
              "@type": "Organization",
              "name": "GrockTool.com",
              "url": "https://grocktool.com"
            },
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            },
            "featureList": [
              "Real-time character counting",
              "Word counting with space detection",
              "Sentence detection and counting",
              "Paragraph separation analysis",
              "Characters without spaces calculation",
              "Copy statistics feature"
            ]
          })}
        </script>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": faqData.map(faq => ({
              "@type": "Question",
              "name": faq.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
              }
            }))
          })}
        </script>
      </Head>
      
      <div className="min-h-screen bg-background font-inter">
        <div className="pt-20 pb-8 px-4 sm:pt-24 sm:pb-12 sm:px-6 lg:pt-28">
          <div className="max-w-lg mx-auto lg:max-w-4xl">
            {/* Header */}
            <div className="mb-8 sm:mb-10">
              <Link
                href="/tool"
                className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6 transition-colors group text-sm sm:text-base"
              >
                <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
                Back to Text Tools
              </Link>
              
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="text-center"
              >
                <h1 className="text-2xl sm:text-3xl font-bold text-foreground mb-3">
                  Word & Character Counter
                </h1>
                <p className="text-muted-foreground text-sm sm:text-base">
                  Count words, characters, sentences, and paragraphs instantly
                </p>
              </motion.div>
            </div>

            {/* Main Tool Card */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="bg-card rounded-xl sm:rounded-2xl border border-border p-4 sm:p-6 mb-6 shadow-sm"
            >
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Text Input Section */}
                <div className="lg:col-span-2 space-y-4">
                  <label className="block text-sm font-medium text-foreground">
                    Enter your text:
                  </label>
                  <textarea
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    placeholder="Start typing or paste your text here..."
                    className="w-full min-h-[300px] p-4 bg-input border border-border rounded-lg sm:rounded-xl focus:outline-none focus:ring-1 sm:focus:ring-2 focus:ring-ring focus:ring-opacity-50 resize-none text-foreground placeholder-muted-foreground"
                  />
                  
                  {/* Action Buttons */}
                  <div className="flex gap-3">
                    <button
                      onClick={handleClear}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-secondary text-secondary-foreground rounded-lg sm:rounded-xl hover:bg-secondary/80 transition-colors text-sm sm:text-base"
                    >
                      <RotateCcw size={16} className="sm:w-4 sm:h-4" />
                      Clear All
                    </button>
                    <button
                      onClick={handleCopy}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-accent text-accent-foreground rounded-lg sm:rounded-xl hover:bg-accent/80 transition-colors text-sm sm:text-base"
                    >
                      <Copy size={16} className="sm:w-4 sm:h-4" />
                      Copy Stats
                    </button>
                  </div>
                </div>

                {/* Statistics Section */}
                <div className="space-y-4">
                  <h3 className="text-sm font-medium text-foreground">Statistics</h3>
                  <div className="space-y-3">
                    <div className="bg-secondary rounded-lg p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <Hash size={16} className="text-blue-500" />
                        <div className="text-2xl font-bold text-foreground">{stats.characters}</div>
                      </div>
                      <div className="text-xs text-muted-foreground">Characters</div>
                    </div>
                    <div className="bg-secondary rounded-lg p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <Type size={16} className="text-green-500" />
                        <div className="text-2xl font-bold text-foreground">{stats.charactersNoSpaces}</div>
                      </div>
                      <div className="text-xs text-muted-foreground">Characters (no spaces)</div>
                    </div>
                    <div className="bg-secondary rounded-lg p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <FileText size={16} className="text-purple-500" />
                        <div className="text-2xl font-bold text-foreground">{stats.words}</div>
                      </div>
                      <div className="text-xs text-muted-foreground">Words</div>
                    </div>
                    <div className="bg-secondary rounded-lg p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <MessageSquare size={16} className="text-orange-500" />
                        <div className="text-2xl font-bold text-foreground">{stats.sentences}</div>
                      </div>
                      <div className="text-xs text-muted-foreground">Sentences</div>
                    </div>
                    <div className="bg-secondary rounded-lg p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <Layout size={16} className="text-red-500" />
                        <div className="text-2xl font-bold text-foreground">{stats.paragraphs}</div>
                      </div>
                      <div className="text-xs text-muted-foreground">Paragraphs</div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Quick Info Card */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="bg-card rounded-xl sm:rounded-2xl border border-border p-4 sm:p-6 mb-8 shadow-sm"
            >
              <h3 className="text-base sm:text-lg font-semibold text-foreground mb-3">How to Use</h3>
              <div className="space-y-2 text-muted-foreground text-sm">
                <p>
                  This tool provides real-time text analysis with comprehensive statistics for your writing.
                </p>
                <div className="text-xs sm:text-sm space-y-1 pt-2">
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 bg-muted-foreground rounded-full"></div>
                    <span>Type or paste your text in the input area</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 bg-muted-foreground rounded-full"></div>
                    <span>Statistics update automatically as you type</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 bg-muted-foreground rounded-full"></div>
                    <span>Use Clear All to reset the text and statistics</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 bg-muted-foreground rounded-full"></div>
                    <span>Copy Stats to save your analysis results</span>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* SEO Content Section with Dropdowns */}
            <section className="space-y-4">
              {/* What This Tool Does - Dropdown */}
              <article className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
                <button
                  onClick={() => toggleSection('whatItDoes')}
                  className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/50 transition-colors"
                >
                  <h2 className="text-xl font-bold text-foreground">Word Counter Tool - What It Does</h2>
                  {openSections.whatItDoes ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </button>
                
                {openSections.whatItDoes && (
                  <div className="px-6 pb-6">
                    <p className="text-muted-foreground mb-4">
                      This free online word counter provides comprehensive text analysis in real-time, helping writers, students, professionals, and content creators track their writing metrics. The tool instantly calculates five essential statistics: total characters (including spaces), characters without spaces, word count, sentence count, and paragraph count—all updating live as you type or paste text.
                    </p>
                    <p className="text-muted-foreground">
                      Unlike basic counters, our tool handles complex text structures accurately, including proper sentence detection (distinguishing between abbreviations and sentence endings) and paragraph recognition based on standard publishing conventions. Whether you're crafting social media posts with strict character limits, writing academic papers with word count requirements, or analyzing text for SEO optimization, this word counter delivers precise, reliable metrics to support your writing goals.
                    </p>
                  </div>
                )}
              </article>

              {/* Use Cases Section - Dropdown */}
              <article className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
                <button
                  onClick={() => toggleSection('useCases')}
                  className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/50 transition-colors"
                >
                  <h2 className="text-xl font-bold text-foreground">Practical Use Cases for Word Counting</h2>
                  {openSections.useCases ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </button>
                
                {openSections.useCases && (
                  <div className="px-6 pb-6">
                    <p className="text-muted-foreground mb-4">
                      Word counting serves essential purposes across various writing and content creation scenarios:
                    </p>
                    <ul className="space-y-3 text-muted-foreground pl-5">
                      <li className="pl-2">
                        <strong className="text-foreground">Academic Writing & Research Papers</strong>
                        <p className="mt-1">Meeting strict word count requirements for essays, theses, and journal submissions while maintaining proper paragraph structure.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Content Marketing & SEO</strong>
                        <p className="mt-1">Optimizing blog posts and articles for search engines with ideal word counts (typically 1,500-2,500 words for comprehensive coverage).</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Social Media Management</strong>
                        <p className="mt-1">Crafting tweets within 280 characters, Instagram captions, and LinkedIn posts with character limit awareness.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Professional Communications</strong>
                        <p className="mt-1">Writing concise emails, reports, and business documents with appropriate sentence and paragraph lengths for readability.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Creative Writing & Publishing</strong>
                        <p className="mt-1">Tracking novel or short story progress with word count goals and maintaining consistent chapter lengths.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Translation & Localization</strong>
                        <p className="mt-1">Estimating project scope and costs based on word counts for translation services.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Academic & Professional Applications</strong>
                        <p className="mt-1">Adhering to strict character/word limits for resumes, cover letters, grant proposals, and scholarship applications.</p>
                      </li>
                    </ul>
                  </div>
                )}
              </article>

              {/* How to Use This Tool - Dropdown */}
              <article className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
                <button
                  onClick={() => toggleSection('howToUse')}
                  className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/50 transition-colors"
                >
                  <h2 className="text-xl font-bold text-foreground">How to Use This Word Counter Effectively</h2>
                  {openSections.howToUse ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </button>
                
                {openSections.howToUse && (
                  <div className="px-6 pb-6">
                    <ol className="space-y-4 text-muted-foreground pl-5">
                      <li className="pl-2">
                        <strong className="text-foreground">Input Your Text</strong>
                        <p className="mt-1">Type directly into the text area or paste content from any source (documents, websites, emails). The counter updates instantly.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Monitor Real-Time Statistics</strong>
                        <p className="mt-1">Watch the five metrics update as you write: characters, characters without spaces, words, sentences, and paragraphs.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Use for Specific Requirements</strong>
                        <p className="mt-1">Adjust your writing based on specific needs: shorten tweets to 280 characters, expand blog posts to optimal SEO length, or meet academic word counts.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Analyze Text Structure</strong>
                        <p className="mt-1">Review sentence and paragraph counts to ensure readable formatting. Aim for 15-20 words per sentence and 3-5 sentences per paragraph.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Save Your Results</strong>
                        <p className="mt-1">Use the "Copy Stats" button to save all statistics to your clipboard for record-keeping or inclusion in documents.</p>
                      </li>
                      <li className="pl-2">
                        <strong className="text-foreground">Start Fresh When Needed</strong>
                        <p className="mt-1">Use "Clear All" to reset the tool for analyzing new text, maintaining accurate counts for each separate writing project.</p>
                      </li>
                    </ol>
                  </div>
                )}
              </article>

              {/* Example Input and Output - Dropdown */}
              <article className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
                <button
                  onClick={() => toggleSection('examples')}
                  className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/50 transition-colors"
                >
                  <h2 className="text-xl font-bold text-foreground">Word Counter Examples & Analysis</h2>
                  {openSections.examples ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </button>
                
                {openSections.examples && (
                  <div className="px-6 pb-6">
                    <p className="text-muted-foreground text-sm mb-4">
                      Below are examples demonstrating how different types of text produce varying statistical results:
                    </p>
                    <div className="space-y-6">
                      <div>
                        <h3 className="text-lg font-semibold text-foreground mb-2">Example 1: Short Blog Post Introduction</h3>
                        <div className="bg-muted p-4 rounded-lg overflow-x-auto">
                          <pre className="text-sm text-muted-foreground font-mono">
{`Input Text:
"Content marketing has revolutionized how businesses connect with audiences. 
By creating valuable, relevant content, companies build trust and authority. 
This approach differs from traditional advertising because it focuses on 
helping rather than selling. The results? Increased engagement and loyalty."

Analysis Results:
• Characters: 226
• Characters (no spaces): 185
• Words: 43
• Sentences: 4
• Paragraphs: 1

Interpretation:
This 43-word introduction uses relatively short sentences (average 10.75 words)
with good readability. The character-to-word ratio is healthy for SEO content.`}
                          </pre>
                        </div>
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-foreground mb-2">Example 2: Twitter Thread Analysis</h3>
                        <div className="bg-muted p-4 rounded-lg overflow-x-auto">
                          <pre className="text-sm text-muted-foreground font-mono">
{`Input Text:
"Just launched our new product! 🚀 
Game-changing features include:
- AI-powered analytics
- Real-time collaboration
- Customizable dashboards
Available now at our website.
#ProductLaunch #Innovation"

Analysis Results:
• Characters: 153
• Characters (no spaces): 129
• Words: 17
• Sentences: 4
• Paragraphs: 1

Interpretation:
Perfect for Twitter with only 153 characters (well under 280 limit). 
Bullet points reduce word count while maintaining information density. 
Emoji and hashtags included in character count.`}
                          </pre>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </article>

              {/* Frequently Asked Questions - Dropdown */}
              <article className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
                <button
                  onClick={() => toggleSection('faqs')}
                  className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/50 transition-colors"
                >
                  <h2 className="text-xl font-bold text-foreground">Frequently Asked Questions About Word Counting</h2>
                  {openSections.faqs ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </button>
                
                {openSections.faqs && (
                  <div className="px-6 pb-6">
                    <div className="space-y-6">
                      {faqData.map((faq, index) => (
                        <div key={index}>
                          <h3 className="text-lg font-semibold text-foreground mb-2">{faq.question}</h3>
                          <p className="text-muted-foreground">{faq.answer}</p>
                        </div>
                      ))}
                    </div>
                    
                    {/* Professional Disclaimer */}
                    <div className="mt-8 p-4 bg-yellow-500/10 rounded-lg border border-yellow-500/20">
                      <h3 className="text-lg font-semibold text-foreground mb-2">Professional Writing Disclaimer</h3>
                      <p className="text-sm text-muted-foreground">
                        This word counter tool provides statistical analysis based on standard linguistic rules and text processing algorithms. While we strive for accuracy, different applications and platforms may use slightly different counting methodologies. For critical applications like academic submissions, professional publications, or legal documents, always verify word counts using the specific software or platform requirements you're targeting. The tool is designed for guidance and productivity enhancement but should not replace official word count verification when strict requirements exist.
                      </p>
                    </div>
                  </div>
                )}
              </article>

              {/* Related Tools Section - Dropdown */}
              <article className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
                <button
                  onClick={() => toggleSection('faqs')}
                  className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/50 transition-colors"
                >
                  <h2 className="text-xl font-bold text-foreground">Related Text Tools</h2>
                  {openSections.faqs ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </button>
                
                {openSections.faqs && (
                  <div className="px-6 pb-6">
                    <p className="text-muted-foreground mb-4">
                      Explore other useful text tools from GrockTool.com:
                    </p>
                    <ul className="space-y-3 text-muted-foreground">
                      <li className="flex items-start">
                        <span className="text-accent mr-2">•</span>
                        <Link href="/text-tools/remove-duplicates" className="text-accent hover:underline">
                          <strong>Remove Duplicates:</strong> Remove duplicate lines from text
                        </Link>
                      </li>
                      <li className="flex items-start">
                        <span className="text-accent mr-2">•</span>
                        <Link href="/text-tools/case-converter" className="text-accent hover:underline">
                          <strong>Case Converter:</strong> Convert text between different cases
                        </Link>
                      </li>
                      <li className="flex items-start">
                        <span className="text-accent mr-2">•</span>
                        <Link href="/text-tools/text-sorter" className="text-accent hover:underline">
                          <strong>Text Sorter:</strong> Sort lines of text alphabetically
                        </Link>
                      </li>
                      <li className="flex items-start">
                        <span className="text-accent mr-2">•</span>
                        <Link href="/text-tools/text-reverser" className="text-accent hover:underline">
                          <strong>Text Reverser:</strong> Reverse text or word order
                        </Link>
                      </li>
                      <li className="flex items-start">
                        <span className="text-accent mr-2">•</span>
                        <Link href="/text-tools/slug-generator" className="text-accent hover:underline">
                          <strong>Slug Generator:</strong> Create SEO-friendly URL slugs
                        </Link>
                      </li>
                      <li className="flex items-start">
                        <span className="text-accent mr-2">•</span>
                        <Link href="/text-tools/find-replace" className="text-accent hover:underline">
                          <strong>Find & Replace:</strong> Search and replace text patterns
                        </Link>
                      </li>
                    </ul>
                  </div>
                )}
              </article>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}